application: guildachievements
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 1d

- url: /static
  static_dir: static
  expiration: 1d

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

# http://code.google.com/appengine/docs/python/tools/uploadingdata.html
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /shell.*
  script: shell.py
  login: admin

- url: .*
  script: main.py

