application: guildachievements
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: .*
  script: main.py

